Create post
ThomasG51/OC_DAS_P5 pull request #35
Opened 2020-11-16 10:36 UTC by ThomasG51

2020-11-16 10:56 UTC, TBoileau requested changes
Supprimer les fichiers uploadés de tests, et modifier le .gitignore pour ignorer les fichiers uploadés

2020-11-16 10:56 UTC, TBoileau commented on lib/AbstractController.php
> +    public function uploadFile(array $file, string $coverName) : void
Utiliser la propriété `Request`

2020-11-16 10:56 UTC, TBoileau commented on lib/AbstractController.php
> +        $fileTmpName = $file['tmp_name'];
`$request->files->get('NOM`)`, tu récupères un objet [UploadedFile](https://github.com/symfony/http-foundation/blob/5.x/File/UploadedFile.php)

2020-11-16 10:56 UTC, TBoileau commented on lib/AbstractController.php
> +        if(move_uploaded_file($fileTmpName, $directory.$fileName))
`$request->files->get("NOM")->move($directory, $fileName)`

2020-11-16 10:56 UTC, TBoileau commented on lib/AbstractController.php
> +
Implémenter le constructeur en passant comme argument une request, et par conséquent avoir une propriété protected $request que tu pourras réutilisés dans tes contrôleurs.

2020-11-16 10:56 UTC, TBoileau commented on src/Controller/CategoryController.php
> +        $request = Request::createFromGlobals();
Tu ne devrais pas avoir de `Request::createFromGlobals`. Normalement tu devrais la passer la request dans le constructeur de ton contrôleur (cf Route.php), et pouvoir récupérer la request dans chacun de tes contrôleurs `$this->request`

2020-11-16 10:56 UTC, TBoileau commented on src/Controller/CategoryController.php
> +        return $this->redirectToRoute('/post/create');
Envoyer du JSON plutôt qu'une redirection.

2020-11-16 10:56 UTC, TBoileau commented on src/Controller/PostController.php
> +        if($request->request->get('title'))
Tester plutôt si c'est une méthode POST et non s'il y a quelque chose dans $_POST

2020-11-16 10:56 UTC, TBoileau commented on src/Controller/PostController.php
> +            $coverName = uniqid('upload-', TRUE).'.'.pathinfo($_FILES['cover']['name'], PATHINFO_EXTENSION);
La génération du nom unique du fichier devrait se gérer dans la méthode uploadFile de l'abstract contrôleur.

2020-11-16 10:56 UTC, TBoileau commented on src/Controller/PostController.php
> +            }
Tu ne gères pas l'auto-increment ? On ne se soucis pas de l'id.

Pour récupérer l'id qui a été générer par MySQL, utiliser la fonction MySQL [last_insert_id ](https://www.w3schools.com/sql/func_mysql_last_insert_id.asp).

2020-11-16 10:56 UTC, TBoileau commented on src/Controller/TagsController.php
> +        return $this->redirectToRoute('/post/create');
On retourne du JSON.

2020-11-16 10:56 UTC, TBoileau commented on src/Controller/TagsLineController.php
> +}
Inutile, à supprimer, tu gères ça directement dans ton formulaire de création de post.
Un champ select multiple (qui contiendra un tableau d'id de tag) ou avec des checkbox.
```html
<input type="checkbox" name="tags[]" value="{{ tag.id }}" />
```
````php
$this->request->request->get("tags")
```

2020-11-16 10:56 UTC, TBoileau commented on src/Repository/CategoryRepository.php
> +        $query->execute(['name' => $name]);
Ici, faire le last_insert_id pour setter l'identifiant nouvellement créé.

2020-11-16 10:56 UTC, TBoileau commented on src/Repository/PostRepository.php
> +    }
A supprimer, ou à déplacer dans AbstactRepository, mais faire la fameuse requête `SELECT LAST_INSERT_ID`.

2020-11-16 10:56 UTC, TBoileau commented on src/Repository/TagsLineRepository.php
> +        ]);
A déplacer dans la méthode create de PostRepository

2020-11-16 11:18 UTC, ThomasG51 commented on lib/AbstractController.php
> +
Modification faite

2020-11-16 11:18 UTC, ThomasG51 commented on src/Controller/CategoryController.php
> +        $request = Request::createFromGlobals();
Modification faite

2020-11-16 12:18 UTC, ThomasG51 commented on lib/AbstractController.php
> +        $fileTmpName = $file['tmp_name'];
Modification faite

2020-11-16 12:18 UTC, ThomasG51 commented on lib/AbstractController.php
> +    public function uploadFile(array $file, string $coverName) : void
Modification faite

2020-11-16 12:19 UTC, ThomasG51 commented on lib/AbstractController.php
> +        if(move_uploaded_file($fileTmpName, $directory.$fileName))
Modification faite

2020-11-16 13:33 UTC, ThomasG51 commented on src/Controller/PostController.php
> +        if($request->request->get('title'))
Modification faite

2020-11-16 13:34 UTC, ThomasG51 commented on src/Controller/PostController.php
> +            $coverName = uniqid('upload-', TRUE).'.'.pathinfo($_FILES['cover']['name'], PATHINFO_EXTENSION);
Modification faite

2020-11-23 10:59 UTC, TBoileau requested changes

2020-11-23 10:59 UTC, TBoileau commented on lib/AbstractController.php
> +            dd('The file is not an image !');
éviter les dd

2020-11-23 10:59 UTC, TBoileau commented on src/Controller/CategoryController.php
> +        if($this->request->request->get('name'))
tu testes si la request method == post

2020-11-23 10:59 UTC, TBoileau commented on src/Controller/PostController.php
> +            !empty($this->request->request->get('category'))
[Gestion des erreurs](https://gist.github.com/TBoileau/c65a207fe2528a47ad51a75ed3ede464)

2020-11-23 10:59 UTC, TBoileau commented on src/Repository/PostRepository.php
>          return $query->fetchAll();
Au lieu du fetch :
Tu boucles sur ton tableau, et tu retournes un tableau d'instance de Post.

2020-11-23 10:59 UTC, TBoileau commented on src/Repository/PostRepository.php
> +        ]);
si on passe en mode entity, tu passe s pas des données scalaires mais un objet post.

2020-11-23 12:58 UTC, ThomasG51 commented on src/Controller/CategoryController.php
> +        return $this->redirectToRoute('/post/create');
Modification faite

2020-11-23 12:58 UTC, ThomasG51 commented on src/Controller/TagsController.php
> +        return $this->redirectToRoute('/post/create');
Modification faite

2020-11-23 23:14 UTC, ThomasG51 commented on src/Controller/PostController.php
> +            !empty($this->request->request->get('category'))
modification faite

2020-11-25 10:39 UTC, ThomasG51 commented on src/Repository/PostRepository.php
>          return $query->fetchAll();
modification faite

2020-11-30 10:41 UTC, TBoileau approved these changes

2020-11-30 11:01 UTC, merged