feat: create new user with errors management using ajax
ThomasG51/OC_DAS_P5 pull request #36
Opened 2020-11-30 17:20 UTC by ThomasG51

2020-12-14 10:53 UTC, TBoileau requested changes

2020-12-14 10:53 UTC, TBoileau commented on src/Controller/UserController.php
> +            }
Refactoring de cette partie

2020-12-14 10:53 UTC, TBoileau commented on src/Controller/UserController.php
> +            }
```php
if(empty($this->request->request->get('login_email'))) {
    return new JsonResponse(['login_email_error' => 'L\'email ne peut pas être vide']);
}
if(empty($this->request->request->get('login_password'))) {
    return new JsonResponse(['login_password_error' => 'Le mot de passe ne peut pas être vide']);
}
$user = $this->userManager->findOne($this->request->request->get('login_email'));
if($user === null) {
    return new JsonResponse(['login_email_error' => 'Le compte n\'existe **pas']);**
}
if(!password_verify($this->request->request->get('login_password'), $user->getPassword())) {
    return new JsonResponse(['login_password_error' => 'Le mot de passe est incorrect']);
}
$this->session->set('user', $user);
return new JsonResponse(['login_succeeds' => 'Connexion reussi.']);
```

2020-12-14 10:53 UTC, TBoileau commented on src/Controller/UserController.php
> +            }
Refactoring validation formulaire

2020-12-14 10:53 UTC, TBoileau commented on src/Repository/CategoryRepository.php
> +        }
````php
if ($category === null) {
    return null;
}
return new Category($category['id'], $category['name']);
```

2020-12-14 10:53 UTC, TBoileau commented on src/Repository/PostRepository.php
> +        }
Refactoring

2020-12-14 10:53 UTC, TBoileau commented on src/Repository/TagsRepository.php
> +        }
Refactoring

2020-12-14 10:53 UTC, TBoileau commented on src/Repository/UserRepository.php
> +        }
Refactoring

2020-12-16 12:12 UTC, ThomasG51 commented on src/Controller/UserController.php
> +            }
done

2020-12-16 12:12 UTC, ThomasG51 commented on src/Repository/CategoryRepository.php
> +        }
done

2020-12-16 12:12 UTC, ThomasG51 commented on src/Repository/TagsRepository.php
> +        }
done

2020-12-16 12:12 UTC, ThomasG51 commented on src/Repository/UserRepository.php
> +        }
done

2020-12-16 12:12 UTC, ThomasG51 commented on src/Repository/PostRepository.php
> +        }
done

2020-12-16 15:12 UTC, ThomasG51 commented on src/Controller/UserController.php
> +            }
done

2020-12-16 15:12 UTC, ThomasG51 commented on src/Controller/UserController.php
> +            }
done

2020-12-21 10:37 UTC, TBoileau requested changes
Les validateurs doivent se trouver dans `src`

2020-12-21 10:43 UTC, TBoileau requested changes

2020-12-21 10:43 UTC, TBoileau commented on src/Controller/UserController.php
> +                $this->session->set('csrf_token', md5(bin2hex(openssl_random_pseudo_bytes(8))));
Revoir l'utilisation du CSRF

2020-12-21 10:46 UTC, merged