Dev
ThomasG51/OC_DAS_P5 pull request #38
Opened 2020-12-21 10:47 UTC by ThomasG51

2020-12-21 10:54 UTC, TBoileau requested changes

2020-12-21 10:54 UTC, TBoileau commented on src/Entity/Comment.php
> +    private string $date;
Eviter ce genre de wording trop générique, être plus sémantique

2020-12-21 10:54 UTC, TBoileau commented on src/Repository/CommentRepository.php
> +            LEFT JOIN user ON comment.user_id = user.id
Pas de left join, privilégier inner join

2020-12-21 11:54 UTC, ThomasG51 commented on src/Entity/Comment.php
> +    private string $date;
done -> createdAt

2020-12-21 11:55 UTC, ThomasG51 commented on src/Repository/CommentRepository.php
> +            LEFT JOIN user ON comment.user_id = user.id
done

2020-12-28 10:50 UTC, TBoileau requested changes

2020-12-28 10:50 UTC, TBoileau commented on lib/AbstractController.php
> +            return $this->redirectToRoute('/post/create');
On throw des erreurs

2020-12-28 10:50 UTC, TBoileau commented on src/Controller/CommentController.php
> +        }
A mettre dans le show du PostController

2020-12-28 10:50 UTC, TBoileau commented on src/Controller/CommentController.php
> +            return $this->redirectToRoute('/');
Throw Exception

2020-12-28 10:50 UTC, TBoileau commented on src/Controller/CommentController.php
> +            return $this->redirectToRoute('/');
Throw Exception 404

2020-12-28 10:50 UTC, TBoileau commented on src/Controller/CommentController.php
> +            return $this->redirectToRoute('/');
Throw Exception 404

2020-12-28 10:50 UTC, TBoileau commented on src/Controller/PostController.php
> +        }
Throw Exception 404

2020-12-28 10:50 UTC, TBoileau commented on src/Controller/PostController.php
> +        }
Throw Exception 404

2020-12-28 10:52 UTC, TBoileau approved these changes

2021-01-04 10:51 UTC, TBoileau requested changes

2021-01-04 10:51 UTC, TBoileau commented on lib/AbstractController.php
> +            throw new \Exception('Vous n\'avez pas les droits pour effectuer cette opération');
Favoriser l'implémentation d'une classe Exception custom

2021-01-04 10:51 UTC, TBoileau commented on lib/AbstractController.php
> +            throw new \Exception('Vous n\'êtes pas connecté !');
Favoriser l'implémentation d'une classe Exception custom

2021-01-04 10:51 UTC, TBoileau commented on src/Controller/CategoryController.php
> +        if($this->request->request->get('csrf_token') === $this->session->get('csrf_token'))
Refactoring de ce test

2021-01-04 10:51 UTC, TBoileau commented on src/Controller/CommentController.php
> +        return $this->redirectToRoute('/');
Déplacer dans show de PostController

2021-01-04 10:51 UTC, TBoileau commented on src/Controller/HomeController.php
> +            throw new \Exception('La page demandée n\'existe pas', 404);
Dans le cas ou la page n'existe pas, ne pas déclencher d'erreur, mais plutôt afficher la dernière page ou la première selon les cas suivant :
- page < 1
- page > dernière page

2021-01-04 10:51 UTC, TBoileau commented on src/Controller/PostController.php
> +            return $this->redirectToRoute('/');
On lève une exception custom pour générer une 404

2021-01-04 10:51 UTC, TBoileau commented on src/Controller/PostController.php
> +            return $this->redirectToRoute('/');
On lève une exception custom pour générer une 404

2021-01-04 10:51 UTC, TBoileau commented on src/Controller/TagsController.php
> +            return $this->redirectToRoute('/');
On lève une exception custom pour générer une 404

2021-01-04 10:51 UTC, TBoileau commented on src/Controller/UserController.php
> +            return $this->redirectToRoute('/');
On lève une exception custom pour générer une 400

2021-01-04 10:51 UTC, TBoileau commented on src/Controller/UserController.php
> +            return $this->redirectToRoute('/');
On lève une exception custom pour générer une 400

2021-01-04 10:51 UTC, TBoileau commented on src/Repository/CommentRepository.php
> +            LEFT JOIN user ON comment.user_id = user.id
?

2021-01-04 10:51 UTC, TBoileau commented on src/Repository/CommentRepository.php
> +            LEFT JOIN user ON comment.user_id = user.id
INNER JOIN

2021-01-04 10:51 UTC, TBoileau commented on src/Repository/PostRepository.php
>              LEFT JOIN user ON post.user_id = user.id
INNER JOIN

2021-01-04 10:51 UTC, TBoileau commented on src/Repository/PostRepository.php
> +            LEFT JOIN user ON post.user_id = user.id
INNER JOIN

2021-01-05 15:41 UTC, ThomasG51 commented on src/Controller/CommentController.php
> +        }
done

2021-01-05 15:42 UTC, ThomasG51 commented on src/Controller/CommentController.php
> +            return $this->redirectToRoute('/');
done

2021-01-05 15:42 UTC, ThomasG51 commented on src/Controller/PostController.php
> +        }
done

2021-01-05 15:43 UTC, ThomasG51 commented on lib/AbstractController.php
> +            throw new \Exception('Vous n\'êtes pas connecté !');
done

2021-01-05 15:43 UTC, ThomasG51 commented on src/Controller/CommentController.php
> +        return $this->redirectToRoute('/');
done

2021-01-05 15:44 UTC, ThomasG51 commented on src/Controller/HomeController.php
> +            throw new \Exception('La page demandée n\'existe pas', 404);
done

2021-01-05 15:44 UTC, ThomasG51 commented on src/Controller/UserController.php
> +            return $this->redirectToRoute('/');
done

2021-01-05 15:45 UTC, ThomasG51 commented on src/Repository/PostRepository.php
> +            LEFT JOIN user ON post.user_id = user.id
done

2021-01-05 15:46 UTC, ThomasG51 commented on src/Repository/CommentRepository.php
> +            LEFT JOIN user ON comment.user_id = user.id
done

2021-01-05 15:46 UTC, ThomasG51 commented on src/Controller/PostController.php
> +            return $this->redirectToRoute('/');
done

2021-01-05 15:46 UTC, ThomasG51 commented on src/Controller/TagsController.php
> +            return $this->redirectToRoute('/');
done

2021-01-05 15:46 UTC, ThomasG51 commented on src/Controller/UserController.php
> +            return $this->redirectToRoute('/');
done

2021-01-05 15:47 UTC, ThomasG51 commented on src/Controller/CommentController.php
> +            return $this->redirectToRoute('/');
done

2021-01-05 15:47 UTC, ThomasG51 commented on src/Controller/CommentController.php
> +            return $this->redirectToRoute('/');
done

2021-01-05 15:47 UTC, ThomasG51 commented on src/Controller/PostController.php
> +        }
done

2021-01-05 15:47 UTC, ThomasG51 commented on src/Controller/CategoryController.php
> +        if($this->request->request->get('csrf_token') === $this->session->get('csrf_token'))
done

2021-01-05 15:47 UTC, ThomasG51 commented on src/Controller/PostController.php
> +            return $this->redirectToRoute('/');
done

2021-01-05 16:05 UTC, ThomasG51 commented on lib/AbstractController.php
> +            return $this->redirectToRoute('/post/create');
done

2021-01-11 10:41 UTC, TBoileau requested changes

2021-01-11 10:41 UTC, TBoileau commented on lib/AbstractController.php
> +            throw new BadGatewayException('Le fichier n\'est pas une image.', 502);
BadGateway = 502, à remplacer par un BadRequest (400)

2021-01-11 10:41 UTC, TBoileau commented on lib/Exceptions/BadGatewayException.php
> +}
A supprimer

2021-01-11 10:41 UTC, TBoileau commented on lib/mailer/ContactMail.php
> +    }
Eviter l'utilisation de la fonction mail : 
- SwiftMailer

2021-01-11 12:21 UTC, TBoileau approved these changes

2021-01-18 10:31 UTC, ThomasG51 commented on lib/AbstractController.php
> +            throw new BadGatewayException('Le fichier n\'est pas une image.', 502);
done

2021-01-18 10:31 UTC, ThomasG51 commented on lib/Exceptions/BadGatewayException.php
> +}
done

2021-01-18 10:31 UTC, ThomasG51 commented on lib/mailer/ContactMail.php
> +    }
done

2021-01-18 15:28 UTC, closed without merging